### ISSUE TITLE
Assistance getting started with basic kernel function for parallel computation

### ISSUE THREAD

**Issue by JannyKul** [naleksiev/mtlpp#1]
Hi, thank you so much for your brilliant library. I’m just trying to get up and running with a very basic example. My ultimate goal will be using Metal through your library to move some computationally expensive (and “embarrassingly parallel”) operations in C++ from the CPU to the GPU. 

Here is the function I have attempted to put together using your library.

```C++
void SampleMetal(){

    //SET UP METAL - device, library, command queue, command buffer, command encoder
    mtlpp::Library device = mtlpp::Device::CreateSystemDefaultDevice();
    mtlpp::Device library = device.NewDefaultLibrary();
    mtlpp::CommandQueue commandQueue = device.NewCommandQueue();
    mtlpp::CommandBuffer commandBuffer = commandQueue.CommandBuffer();
    assert(device);
    assert(library);
    assert(commandQueue);
    assert(commandBuffer);
    
    //SET UP SHADER - create function, make compute pipeline
    ns::String functionName = "doubleInputValues";
    mtlpp::Function kernelFunction =  library.NewFunction(functionName);
    assert(kernelFunction);
    ns::Error error;
    mtlpp::ComputePipelineState pipelineState = device.NewComputePipelineState(kernelFunction, &error);
    assert(pipelineState);
    
    // CREATE INPUT & OUTPUT
    int i = 50;
    std::vector<int> inputVector(i);
    mtlpp::Buffer inputBuffer = device.NewBuffer(&inputVector, sizeof(inputVector), mtlpp::ResourceOptions::CpuCacheModeDefaultCache); 
    std::vector<int> outputVector(i, 0); 
    mtlpp::Buffer outputBuffer = device.NewBuffer(&outputVector, sizeof(outputVector), mtlpp::ResourceOptions::CpuCacheModeDefaultCache); 
    assert(inputBuffer);
    assert(outputBuffer);
    
    // Create COMPUTE COMMAND CODER
    mtlpp::ComputeCommandEncoder commandEncoder = commandBuffer.ComputeCommandEncoder();
    commandEncoder.SetBuffer(inputBuffer,0,0);
    commandEncoder.SetBuffer(outputBuffer,0,1);
    assert(commandEncoder);
    commandEncoder.SetComputePipelineState(pipelineState);
    
    // Find max number of parallel threads & set up on GPU
    int threadExecutionWidth = pipelineState.GetThreadExecutionWidth();
    mtlpp::Size threadsPerGroup = mtlpp::Size(threadExecutionWidth,1,1);
    mtlpp::Size numThreadGroups = mtlpp::Size(((uint32_t)inputVector.size()+threadExecutionWidth)/threadExecutionWidth,1,1); 
    commandEncoder.DispatchThreadgroups(numThreadGroups, threadsPerGroup);
    
    //finalise
    commandEncoder.EndEncoding();
    commandBuffer.Commit();
    commandBuffer.WaitUntilCompleted();
    
    //output??
    std::string outputString((char *) outputBuffer.GetContents());
    std::cout << "output string: “ << outputString;

}
```

And here is the shader function:

```C++
kernel void doubleInputValues(const device float *inVector [[ buffer(0) ]], device float *outVector [[ buffer(1) ]], uint id [[ thread_position_in_grid ]]) {
    outVector[id] = 2*inVector[id];
}
```

I have some questions I was hoping you’d be able to help with:

1. I can’t seem to get the right output as I couldn’t find how to parse the bytes data from your examples (as they’re all for textures as opposed to computation) - would you mind pointing me in the right direction? It currently outputs some garbage values like `\360\323` and I’m not entirely sure what I’m doing wrong although I’m sure the issue is probably in the `GetContents()` line at the end of the `SampleMetal()` function.

2. I’d be using the function as part of processing video in real time, am I supposed to set up Metal, set up the Shader etc for every frame or are there parts that only need to be created once like setting up Metal and the Shader and then just assigning input and output vectors for each video frame? I did try doing this but got a crash of `EXC_BAD_ACCESS` on the `computeCommandEncoder` pointer so wasn’t sure if it’s possible. (I know this is more of a Metal API question but I wasn’t sure if the issue was related to my incorrect implementation of your library).

3. The entire function runs in about 4 milliseconds on an iPhone 6 plus, is that supposed to be correct or is there something I’m doing horribly inefficiently as I would have thought simply running a doubling operation on 50 values should be much less time. I’m trying to get some CPU work offloaded onto the GPU to get video processing nearer to 60fps so would like some insight on how to make this as fast as possible before I start building more complicated shaders.

Thank you very much for your help and for building this library!

**Comment by naleksiev** [comment]
Hi. First of all I added a quick compute example so please check that. Now about your questions:
1. There are couple of thinks I see right away. First the inputVector data is not initialized. And second your input/output vectors are of type int where your shader reinterprets the data as float.
2. The example I added also includes multiple iterations. It does reuse most of the objects including the input/output Buffers.
3. The function includes device creation, shader compilation, pipeline creation, buffer creation, etc. Move all of it into init step and then measure again only the per frame work. Also kicking some tiny task on GPU and synchronizing with CPU immediately is not the best you can do. You don't want the GPU to wait for the CPU to queue a task and then the CPU to wait for the GPU to finish the task. They are 2 separate units and you want them to work in parallel. Queue more work for the GPU and consume it from the CPU when you need it. For example create 4 sets of input/output Buffers and CommandBuffers. Fill the input buffers with the data for frame 1, 2, 3, 4 dispatch each frame on different CommandBuffer and Commit them in the right order. Then for CommandBuffer with frame 1 WaitUntilCompleted, read the data, fill the input buffer with the data for frame 5 and Commit again.

Hopefully this helps.

**Comment by JannyKul** [comment]
Definitely helps, greatly appreciated!
