### ISSUE TITLE
Python wrapper

### ISSUE THREAD

**Issue by mattpaletta** [naleksiev/mtlpp#15]
Hi,

Love the project.  I was trying to wrap your code so I could use it in Python with my ML projects.  Here's what I have so far: `https://github.com/mattpaletta/PyMetal`  At the moment I believe the issue is it fails to link the metal library.

Any suggestions or improvements?
Thanks.

**Comment by naleksiev** [comment]
I just added `extra_objects=["mtlpp.o"],` to your setup.py right after `language="c++",`.

And seems to work:

```
>>> import pymtlpp
>>> mtl = pymtlpp.PyMetal()
>>> mtl.runTest()
sqr(0) = 0
sqr(1) = 1
sqr(2) = 4
sqr(3) = 9
sqr(4) = 16
sqr(5) = 25
sqr(10) = 100
sqr(11) = 121
sqr(12) = 144
sqr(13) = 169
sqr(14) = 196
sqr(15) = 225
sqr(20) = 400
sqr(21) = 441
sqr(22) = 484
sqr(23) = 529
sqr(24) = 576
sqr(25) = 625
sqr(30) = 900
sqr(31) = 961
sqr(32) = 1024
sqr(33) = 1089
sqr(34) = 1156
sqr(35) = 1225
0
>>> 
```

**Comment by mattpaletta** [comment]
@naleksiev Thank you so much!  Ugh, I was so close! :)
