### ISSUE TITLE
Triangle Example prints all zeros

### ISSUE THREAD

**Issue by randallrvr** [naleksiev/mtlpp#2]
Assuming the intended output is something more interesting?

randallr-mac:macos_10.12 randallr$ ./02_triangle 
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00

**Comment by naleksiev** [comment]
I tried the examples only on Intel GPU (integrate graphics). I'm assuming you are running on different GPU. 

Before reading a Buffer from CPU it should be synchronized. The latest version should have this fixed. Can you please verify this?

And yes the output should be a bit more interesting:
```
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 FF FF 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 FF FF 00 00 00 00 00 00 00 
00 00 00 00 00 00 FF FF FF FF 00 00 00 00 00 00 
00 00 00 00 00 00 FF FF FF FF 00 00 00 00 00 00 
00 00 00 00 00 FF FF FF FF FF FF 00 00 00 00 00 
00 00 00 00 00 FF FF FF FF FF FF 00 00 00 00 00 
00 00 00 00 FF FF FF FF FF FF FF FF 00 00 00 00 
00 00 00 00 FF FF FF FF FF FF FF FF 00 00 00 00 
00 00 00 FF FF FF FF FF FF FF FF FF FF 00 00 00 
00 00 00 FF FF FF FF FF FF FF FF FF FF 00 00 00 
00 00 FF FF FF FF FF FF FF FF FF FF FF FF 00 00 
00 00 FF FF FF FF FF FF FF FF FF FF FF FF 00 00 
00 FF FF FF FF FF FF FF FF FF FF FF FF FF FF 00 
00 FF FF FF FF FF FF FF FF FF FF FF FF FF FF 00 
FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF 
```

**Comment by randallrvr** [comment]
Yup, that worked, thanks!
