### ISSUE TITLE
Windowed Metal App

### ISSUE THREAD

**Issue by randallrvr** [naleksiev/mtlpp#3]
Not sure I understand the comments about toll-free bridging?  What's the best way to create a fairly minimal windowed Metal app with a render loop?  The 99_view_controller.mm example seems to be missing some header files.

**Comment by naleksiev** [comment]
The comment about toll-free bridging was intended to help with C++ and ObjC interop.
99_view_controller.mm is the ViewController from the Xcode Game template, where Metal is replaced with mtlpp.

I also added 04_window.cpp example which is a short example of what you need. There are 2 more files window.hpp and window.mm which are also necessary. (The 04_window example is macOS only. I'll add iOS and tvOS support soon.)

Hopefully this is helpful.

**Comment by randallrvr** [comment]
Thanks! That is incredibly helpful!
