### ISSUE TITLE
Can add Metal 2 support? 

### ISSUE THREAD

**Issue by oscarbg** [naleksiev/mtlpp#4]
needs new MacOS 10.13 and Xcode 9..

**Comment by naleksiev** [comment]
Yes, I'm already looking into this.

**Comment by oscarbg** [comment]
Only one question.. do you plan to support it in the beta period or will have support once MacOS/IOS and Xcode 9 have stable releases?
thanks

**Comment by naleksiev** [comment]
Yes, I'm planning to support it. I'm working on it, it's pretty big change.
