### ISSUE TITLE
Any chance for a Cmake based example?

### ISSUE THREAD

**Issue by ghost** [naleksiev/mtlpp#5]
Hi,
I am using Clion, with Cmake. I can build and execute your examples from the command line, and I added the required dependency as follows:
``
arget_link_libraries(DeepSleepUITarget
	${OPENGL_LIBRARIES}
		${CMAKE_CURRENT_SOURCE_DIR}/libs/mtlpp.o
	${ARMADILLO_LIBRARIES}
	${GLFW_LIB}
        ${Boost_LIBRARIES}
``

However, during runtime, I get lots of errors such as:
``
/Applications/CLion.app/Contents/bin/cmake/bin/cmake --build /Volumes/1tb-ext/2019/db/stan/Dropbox/dev2/cpp/DeepSleepGUI --target DeepSleepUITarget -- -j 8
[ 25%] Linking CXX executable DeepSleepUITarget
Undefined symbols for architecture x86_64:
  "_CFRelease", referenced from:
      __ZN2ns6ObjectD2Ev in mtlpp.o
      __ZN2ns6ObjectaSERKS0_ in mtlpp.o
      __ZN2ns6ObjectaSEOS0_ in mtlpp.o
  "_CFRetain", referenced from:
      __ZN2ns6ObjectC2ERKNS_6HandleE in mtlpp.o
      __ZN2ns6ObjectC2ERKS0_ in mtlpp.o
      __ZN2ns6ObjectaSERKS0_ in mtlpp.o
  "_MTLCopyAllDevices", referenced from:
      __ZN5mtlpp6Device14CopyAllDevicesEv in mtlpp.o
  "_MTLCreateSystemDefaultDevice", referenced from:
``

I understand that I have missing flags, but not sure how/what to add them in Cmake. 

Thanks,

**Comment by ghost** [comment]
Got that figured out :)

![deepsleepui_cpp_-_deepsleepuitarget_-___volumes_1tb-ext_2019_db_stan_dropbox_dev2_books_2019_bml_kaggle_swift_mtlpp-metal_](https://user-images.githubusercontent.com/18743986/28122306-7d6cc00c-6726-11e7-885a-aa559b8e6b3a.png)

Now there is a complile warning about the types not being compatible, ant idea why?

**Comment by naleksiev** [comment]
Can you post the actual warning/error text not a screenshot of the IDE?

**Comment by naleksiev** [comment]
My guess is that your warning has something to do with the forward declaration of mtlpp::ComputeCommandEncoder. The type is used in function declaration as incomplete (forward declared) type. I tried enabling -Wextra and -Wpedantic but couldn't get any extra warnings. 
What compiler are you using? 
Can you post the command line and the actual warning?
Are you using the amalgamated version of mtlpp or the the headers from src/ folder?

**Comment by naleksiev** [comment]
No plans for cmake.
